version: "3.1"

services:
  db:
    container_name: database
    image: postgres:12
    environment:
      POSTGRES_DB: seafight_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty0207
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postqresql/data

  redis:
    container_name: redisstorage
    image: redis


  tgbot:
    container_name: bot
    build: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
