version: "3.1"

services:
  db:
    container_name: database
    image: postgres:12
    environment:
      - .env
    restart: always

  redis:
    container_name: redisstorage
    image: redis


  tgbot:
    container_name: bot
    build: .
    command: python app.py
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
